server:
  port: 8080
spring:

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: admin
    url: jdbc:mysql://localhost:3306/user-registration
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true